import type { Icon } from "@phosphor-icons/react";
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowsClockwise,
  Bell,
  Briefcase,
  Building,
  CalendarBlank,
  CalendarCheck,
  CalendarDots,
  CaretDoubleLeft,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartBar,
  ChartLineUp,
  ChatCircle,
  Check,
  CheckCircle,
  ClipboardText,
  Clock,
  Command,
  DotsThree,
  DownloadSimple,
  Envelope,
  Eye,
  FileText,
  FileX,
  FloppyDisk,
  Funnel,
  FunnelSimple,
  Gear,
  Gift,
  GlobeHemisphereEast,
  Headphones,
  House,
  Info,
  Laptop,
  Link,
  ListBullets,
  MagnifyingGlass,
  MapPin,
  Minus,
  PaperPlaneTilt,
  PencilSimple,
  PencilSimpleLine,
  Plus,
  Robot,
  ShieldCheck,
  SlidersHorizontal,
  Sparkle,
  Star,
  Target,
  TextB,
  TextItalic,
  TextUnderline,
  User,
  Users,
  X,
} from "@phosphor-icons/react/ssr";

export type LucideIcon = Icon;

export {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  TextB as Bold,
  Bell,
  Robot as Bot,
  Briefcase as BriefcaseBusiness,
  Building as Building2,
  CalendarCheck as CalendarCheck2,
  CalendarDots as CalendarClock,
  CalendarBlank as CalendarDays,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretDoubleLeft as ChevronsLeft,
  ChartBar as BarChart3,
  ChartLineUp as ChartNoAxesCombined,
  ChatCircle as MessageCircle,
  Check,
  CheckCircle as CheckCircle2,
  ClipboardText as ClipboardCheck,
  Clock as Clock3,
  Command,
  DotsThree as MoreHorizontal,
  DownloadSimple as Download,
  PencilSimple as Edit3,
  Eye,
  Archive as FileArchive,
  FileText,
  FileX as FileWarning,
  Funnel as Filter,
  Gift,
  GlobeHemisphereEast as Globe2,
  Headphones,
  House as Home,
  Info,
  TextItalic as Italic,
  Laptop,
  Link as Link2,
  ListBullets as List,
  ListBullets as Menu,
  FunnelSimple as ListFilter,
  MagnifyingGlass as Search,
  Envelope as Mail,
  MapPin,
  Minus,
  PencilSimpleLine as PenLine,
  Plus,
  ArrowsClockwise as RefreshCw,
  FloppyDisk as Save,
  PaperPlaneTilt as Send,
  Gear as Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkle as Sparkles,
  Star,
  Target,
  TextUnderline as Underline,
  User as UserRound,
  Users as UsersRound,
  X,
};
