export {
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bank as Landmark,
  Bell,
  BookmarkSimple as Bookmark,
  Brain,
  Briefcase,
  Briefcase as BriefcaseBusiness,
  Buildings as Building2,
  Calendar,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  ChartBar,
  ChartLine,
  ChartPie as PieChart,
  ChatsCircle as MessagesSquare,
  Check,
  CheckCircle,
  Clock,
  Code as Code2,
  Coins,
  Compass,
  CreditCard as WalletCards,
  DeviceMobile as Smartphone,
  EnvelopeSimple as Mail,
  Eye,
  FacebookLogo as Facebook,
  FileText,
  Fire as Flame,
  GithubLogo as Github,
  Globe,
  GraduationCap,
  Lightning as Zap,
  LinkedinLogo as Linkedin,
  List as Menu,
  MagnifyingGlass as Search,
  MapPin,
  Monitor,
  Moon,
  Newspaper,
  PaperPlaneTilt,
  Path as Route,
  Phone,
  Plus,
  Robot as Bot,
  SealCheck as BadgeCheck,
  ShareNetwork,
  ShieldCheck,
  SlidersHorizontal,
  Sparkle as Sparkles,
  SquaresFour as LayoutGrid,
  Stack as Layers,
  Star,
  Sun,
  TrendUp as TrendingUp,
  UsersThree as UsersRound,
  X,
  YoutubeLogo as Youtube,
} from "@phosphor-icons/react";
